name: Trigger eco-routes Release on Any Tag

on:
  push:
    tags:
      - '*' # Trigger on any tag
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional tag number (without 'v' prefix)"
        required: false
        type: string
jobs:
  trigger-eco-routes:
    name: Trigger eco-routes Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Get Tag Name
        id: get_tag
        run: |
          if [[ -n "${{ inputs.tag }}" ]]; then
            # If manual input is provided
            TAG_VALUE="${{ inputs.tag }}"
            # Add v prefix if not already present
            if [[ ! "$TAG_VALUE" =~ ^v ]]; then
              TAG_VALUE="v$TAG_VALUE"
            fi
            echo "TAG_NAME=$TAG_VALUE" >> $GITHUB_OUTPUT
          else
            # Extract tag from ref
            TAG_VALUE="${GITHUB_REF#refs/tags/}"
            # Fallback if not triggered by tag
            if [[ "$TAG_VALUE" == "${GITHUB_REF}" ]]; then
              TAG_VALUE="v1.1.1999"
            else
              # Add v prefix if not already present
              if [[ ! "$TAG_VALUE" =~ ^v ]]; then
                TAG_VALUE="v$TAG_VALUE"
              fi
            fi
            echo "TAG_NAME=$TAG_VALUE" >> $GITHUB_OUTPUT
          fi

          # Debug info
          echo "Using tag: $TAG_VALUE"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"

      - name: Trigger eco-routes Workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: eco/er-test
          event-type: eco-chains-tag-pushed
          client-payload: '{"tag": "${{ steps.get_tag.outputs.TAG_NAME }}", "environment": "mainnet", "repository": "${{ github.repository }}", "sha": "${{ github.sha }}"}'

      - name: Log Workflow Info
        run: |
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Reference: ${GITHUB_REF}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Successfully dispatched event to eco-routes repository with tag ${{ steps.get_tag.outputs.TAG_NAME }}"
